blueprint:
  name: Philips Tap Dial Switch
  description: 'Control brightness of one light with the dial on a Philips Hue Tap Switch. Use the four buttons
    to assign your own actions.'
  source_url: https://github.com/Hofmanix/ha_blueprints/blob/main/philips_hue_tap_dial_switch_2.yaml
  domain: automation
  input:
    remote:
      name: Philips Hue Tap Switch
      selector:
        device:
          integration: hue
          manufacturer: Signify Netherlands B.V.
          multiple: false
    dimmable_light:
      name: Dimmable Light
      description: The light to be controlled with the dial
      selector:
        target:
          entity:
            domain: light
    button_1_press:
      name: Button 1 Press
      description: Action to run in a single press of button 1
      default: []
      selector:
        action: {}
    button_2_press:
      name: Button 2 Press
      description: Action to run in a single press of button 2
      default: []
      selector:
        action: {}
    button_3_press:
      name: Button 3 Press
      description: Action to run in a single press of button 3
      default: []
      selector:
        action: {}
    button_4_press:
      name: Button 4 Press
      description: Action to run in a single press of button 4
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  subtype: '{{ trigger.event.data.subtype }}'
  type: "{{ trigger.event.data.type }}"
  steps: "{{ trigger.event.data.steps }}"

trigger:
- platform: event
  event_type: hue_event
  event_data:
    device_id: !input remote
action:
  - choose:
    # Dial rotatation
    - conditions:
      - '{{ subtype == "clock_wise" }}'
      sequence:
        - service: light.turn_on
          target: !input dimmable_light
          data:
            brightness_step_pct: '{{ steps }}'
            transition: 1
    - conditions:
      - '{{ event == "counter_clock_wise" }}'
      sequence:
        - service: light.turn_on
          target: !input dimmable_light
          data:
            brightness_step_pct: '{{ -steps }}'
            transition: 1
    # Buttons
    - conditions:
      - '{{ type == "short_release" }}'
      - '{{ scene == 1 }}'
      sequence: !input button_1_press
    - conditions:
      - '{{ type == "short_release" }}'
      - '{{ scene == 2 }}'
      sequence: !input button_2_press
    - conditions:
      - '{{ type == "short_release" }}'
      - '{{ scene == 3 }}'
      sequence: !input button_3_press
    - conditions:
      - '{{ type == "short_release" }}'
      - '{{ scene == 4 }}'
      sequence: !input button_4_press